### ISSUE TITLE
WARCViralWriterProcessor and revisits?

### ISSUE THREAD

**Issue by PsypherPunk** [ukwa/bl-heritrix-modules#3]
Currently we're skipping writing revisit records with the WARCViralWriterProcessor (i.e. `writeRevisitForIdenticalDigests` is `false`).

We need to verify that this kludge can actually handle revisits correctly.

**Comment by anjackson** [comment]
This is not worth the additional complexity, for such a small fraction of the content. Won't-fix for now.
